/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.githubb.wmartinmimi.lilhttpserver4j;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
